name: autodeploy dealcheckers page

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Convert owner to lowercase
        run: |
          echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build image
        run: |
          docker build -t ghcr.io/${OWNER_LC}/energysales:latest .

      - name: Push image
        run: |
          docker push ghcr.io/${OWNER_LC}/energysales:latest

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.1.0
        env:
          OWNER_LC: ${{ env.OWNER_LC }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.ENERGY_WEBSITE_KEY }}
          script: |
            echo "OWNER: $OWNER_LC"
            echo "Pulling: ghcr.io/$OWNER_LC/energysales:latest"

            docker pull ghcr.io/$OWNER_LC/energysales:latest
            docker stop energysales || true
            docker rm energysales || true

            docker run -d \
              -p ${{ secrets.PORT }}:80 \
              --name energysales \
              ghcr.io/$OWNER_LC/energysales:latest
